parameters: {}
environment:
  API_KEY: ${API_KEY}
packages:
    - name: meal
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: plan
          binary: false
          main: ""
          runtime: nodejs:18
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
